# Generated by Django 4.2.5 on 2023-12-27 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tiempo_suficiente', models.BooleanField()),
                ('actividades_interesantes', models.BooleanField()),
                ('material_agradable', models.BooleanField()),
                ('trabajo_fuera_aula', models.BooleanField()),
                ('involucrados', models.CharField(choices=[('TODOS', 'TODOS'), ('ALGUNOS', 'ALGUNOS'), ('POCOS', 'POCOS')], max_length=10)),
                ('atentos', models.CharField(choices=[('TODOS', 'TODOS'), ('ALGUNOS', 'ALGUNOS'), ('POCOS', 'POCOS')], max_length=10)),
                ('interrupciones', models.BooleanField()),
                ('influencias', models.TextField()),
                ('situacion_relevante', models.TextField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
