# Generated by Django 4.2.5 on 2023-11-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_journal', '0003_alter_registro_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
