# Generated by Django 4.2.5 on 2023-12-27 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_school', models.CharField(max_length=90, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('nit', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=90)),
            ],
        ),
    ]
