# Generated by Django 4.2.5 on 2023-11-27 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_school', models.CharField(max_length=90)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('nit', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=90)),
            ],
        ),
    ]
