# Generated by Django 4.2.5 on 2023-11-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name_school',
            field=models.CharField(max_length=90, unique=True),
        ),
    ]
